from typing import Any
from collections.abc import Mapping


BAN_WORDS = {
    "царапин",
    "ремонт",
    "потертости",
    "потерто",
    "скол",
    "пятна",
    "замена",
    "пиксель",
    "на экране",
    "мятый",
    "мятые",
    "мятая",
    "открытый",
    "открыт",
    "дефект",
    "вскрыт",
    "реболл",
    "no charger",
    "без пломб",
    "прошит",
    "угол",
    "экран",
    "актив",
    "уцен",
    "уценка",
    "обме",
    "обменка",
    "короб",
    "пломба",
    "ремешок",
    "зарядн",
    "дисковод",
    "blackview",
    "realme",
    "rfb",
    "asis",
    "cpo",
    "freebuds",
    "pixel buds",
    "oneplus buds",

    "adapter",
    "кабель",
    "charge cable",
    "usb-c 25w",
    "usb-с lightning",
    "магез case",
    "magez case",
    "pitaka",
    "20w",
    "муляж",
    "кожа",
    "silicon",
    "grip case",
    "sult case",
    "folio",
    "чехол",
    "box",
    "ухо",
    "пульт",
    "лампа",
    "кнопка",
    "датчик",
    "насадка",
    "насад",
    "панель",
    "сумк",
    "расческа",
    "earpods",
    "deppo",

    "оптом",
    "прайс",
    "скидка",
    "discount",
    "цена",
    "оплата",
    "гарантия",
    "наличие",
    "поступление",
    "заказ",
    "заказать",
    "пишите",
    "вопросам",
    "отдельности",
    "остальн",
    "новые",
    "новы",
    "запак",
    "распак",
    "фото",
    "упаковка",
    "вилка",
    "совместимость",
    "подходят",
    "включ",
    "пломба",
    "трубный",
    "от",
    "для",
    "штук",
    "шт",
    "по",
    "рублей",
    "картой",
    "сертификат",
    "обслуживание",
    "самовывоз",
    "выдача",
    "доставка",
    "адрес",
    "график",
    "оформление",
    "расчет",
    "телефоны",
    "смартфоны",
    "планшеты",
    "аксессуары",
    "наушники",
    "приставки",
    "консоли | геймпады",
    "игры",

    # Поставщики и контакты
    "mihonor",
    "miopt",
    "likemob",
    "vsemi",
    "infinity",
    "racmag",
    "арти opt",
    "arti opt",
    "л27",
    "николай",
    "ан톤",
    "антон",
    "bekkorolev",
    "rustam",
    "alikson",
    "nechno",
    "https",
    "telegram",
    "price",
    "москва",
    "метро",
    "тяк",
    "магазин",
    "канал",
    "восход",
    "пав",
    "павильон",
    "горбушка",
    "khalidvu_opt",
    "apple_garmin",
    "mta",

    "realme",
    "infinix",
    "tecno",
    "inoi",
    "blackview",
    "a03s",
    "fneh3",
    "ctoned",
    "xenium",

    "airpods 2 l",
    "airpods 2 r",
    "airpods 2 box",
    "airpods 3 l",
    "airpods 3 r",
    "airpods 3 box",
    "airpods 4 l",
    "airpods 4 r",
    "airpods 4 box",
    "airpods pro l",
    "airpods pro r",
    "airpods pro 2023 l",
    "airpods pro 2023 r",
    "airpods pro 2023 box",
    "airpods pro type - c box",
    "airpods pro usb - c l",
    "airpods pro usb - c r",
    "airpods pro usb - c box",
    "airpods pro 2 type-c l",
    "airpods pro 2 type-c r",
    "airpods pro 2 usb-c l",
    "airpods pro 2 usb-c r",
    "airpods pro 2 usb-c box",
    "airpods pro 2 box",
    "airpods 2 case",
    "airpods pro 2 type-c left",
    "airpods 3 anc l",
    "airpods 3 anc r",
    "airpods 4 anc l",
    "airpods 4 anc r",
    "airpods 4 anc box",

    '"a"',
    '"b"',
    '"c"',
    '"a+"',
    '"b+"',
    '"c+"',
    '"a-"',
    '"b-"',
    '"c-"',
    '"а"',
    '"в"',
    '"с"',
    '"а+"',
    '"в+"',
    '"с+"',
    '"а-"',
    '"в-"',
    '"с-"',
}

AIRPODS_PART_WORDS = (
    "left",
    "левый",
    "right",
    "правый",
    "case",
    "кейс",
    "box",
    "футляр"
)


def ban_word(value: Any) -> bool:
    text = str(value or "").casefold()

    if "airpods" in text and any(
        part in text for part in AIRPODS_PART_WORDS
    ):
        return True

    return any(
        banned.casefold() in text
        for banned in BAN_WORDS
    )


def row_has_banned_word(row: Any) -> bool:
    if isinstance(row, Mapping):
        return any(
            row_has_banned_word(value)
            for value in row.values()
        )

    if isinstance(row, (list, tuple, set)):
        return any(
            row_has_banned_word(value)
            for value in row
        )

    return ban_word(row)